My three plots:

1.  depth profiles of concentration of nitrogen and carbon vs depth (dual axis plot)

```{r include = FALSE, message = FALSE, warning = FALSE}
# loading libraries and fonts for plots
library(tidyverse)
library(showtext)
library(here)
library(patchwork)
library(sysfonts)
library(ggtern)
library(lubridate)
library(rcartocolor)
library(scales)
library(ggridges)
font_add_google(name = 'Josefin Sans', family = 'josefin')
font_add_google(name = 'Inter', family = 'inter')

showtext_auto()

# loading in data
nutrient_data <- read_csv(here::here('data','HOT_Bottle_ALOHA.csv'))

# preliminary data cleaning
nutrient_clean <- nutrient_data %>% 
  select(botid_HOT,time,doc_bottle_hot,don_bottle_hot,depth,chl_bottle_hot, botid_HOT,ph_bottle_hot, oxygen_ctd_bottle_hot, NO2_NO3_bottle_hot,temperature_ctd_bottle_hot) %>% # selecting columns of interest
  na.omit() %>% # removing NAs
  # only keeping observations with depth less than or equal to 80 m below sea level
  rename(bottle_id = botid_HOT,
         dissolved_c = doc_bottle_hot,
         dissolved_n = don_bottle_hot,
         ph = ph_bottle_hot,
         chlorophyll = chl_bottle_hot,
         oxygen = oxygen_ctd_bottle_hot,
         temperature = temperature_ctd_bottle_hot)
```

```{r message = FALSE}
# scaling coefficient
coeff <- 10
# 999933 - Nitrogen 
# 117733 - carbon

# subsetting dataset to only have 80m below sea level
nutrient_clean_2 <- nutrient_clean %>% 
  filter(depth <= 80) %>% 
  mutate(avg_n = mean(dissolved_n),
         avg_c = mean(dissolved_c),
         depth_group = case_when(depth <= 20 ~ 'shallow',
                                 depth <= 40 ~ 'medium',
                                 depth <= 60 ~ 'medium deep',
                                 depth <= 80 ~ 'deep'))

avg_dissolved_n <- nutrient_clean_2$avg_n[1]

avg_dissolved_c <- nutrient_clean_2$avg_c[1]

ggplot(nutrient_clean_2, aes(x = depth))+
  geom_line(aes(y = dissolved_n, color = "Nitrogen"))+
  geom_hline(yintercept = avg_dissolved_n, color = "#CC6677",
             linetype = 'dotted')+
  geom_hline(yintercept = avg_dissolved_c/coeff, color = '#44AA99',
             linetype = 'dotted')+
  geom_line(aes(y = dissolved_c/coeff, color = "Carbon"))+
  scale_y_continuous(name = 'Dissolved Nitrogen (µmol/kg)',
                     sec.axis = sec_axis(~.*coeff, 
                                         name = 'Dissolved Carbon (µmol/kg)'))+
  scale_color_manual(values = c('Nitrogen' = '#999933',
                                'Carbon' = '#117733'))+
  labs(x = 'Depth (m)',
       title = 'Depth Profile Comparison of Dissolved Carbon and Nitrogen',
       tag = "Data Source: Hawaiian Ocean Time-series (HOT)")+
  scale_x_reverse()+
  theme(aspect.ratio = 2,
        axis.title.x = element_text(family = 'inter', size = 14),
        axis.title.y = element_text(family = 'inter', size = 14),
        plot.title = element_text(family = 'josefin', size = 18, hjust = .5),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey"),
        axis.text.x= element_text(size = 14),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(family = 'inter', size = 14),
        plot.tag.position = c(0.9999,0))+
  annotate("text", x = 60, y = 4.5, 
           label = 'Average concentration: 5.8 (µmol/kg)', 
           angle = -90, size = 4)+
  annotate("text", x= 60, y = 11.5, 
           label = 'Average concentration: 95.1 (µmol/kg)', angle = -90, size = 4)+
  coord_flip()

```

2.  Depth profile of chlorophyll and its relationship to pH and dissolved oxygen

```{r warning = FALSE, message = FALSE}
# scaling pH and dissolved oxygen to match chlorophyll 
o_coeff <- 100
ph_coeff <- 10


cols <- c('#edf8e9', '#bae4b3',"#74c476", '#238b45')
ggplot(data = nutrient_clean_2,aes(y= oxygen, x = depth))+
  geom_boxplot(aes(fill = depth_group), alpha = 0.75, outlier.color =  "#54278f", outlier.shape = 17, outlier.size = 2)+
  geom_point(aes(x = depth, y = oxygen), alpha = 0.25)+
  scale_fill_manual(values = rev(cols),
                    labels = c('(60 < depth <80) ',
                                 '(40 < depth < 60)',
                                 '(20 < depth < 40)',
                                 ' (20 < depth < 0)'))+
  scale_x_reverse()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8))+
  labs(fill = 'Water Depth (m)',
       y = 'Bottle CTD Oxygen (µmol/kg)',
       x = 'Depth (m)',
       title = 'Oxygen Concentration and its Relationship \nto Depth and pH within the Epipelagic Zone',
       tag = "Data Source: Hawaiian Ocean Time-series (HOT)")+
  coord_flip()+
  theme(axis.title.x = element_text(family = 'inter', size = 14, 
                                    margin = margin(10,0,0,0)),
        axis.title.y = element_text(family = 'inter', size = 14,
                                    margin = margin(0,10,10,0)),
        plot.title = element_text(family = 'josefin', size = 18, hjust = .5, lineheight = 1),
        legend.title = element_text(family = 'inter', size = 16, hjust = .5),
        legend.text = element_text(family = 'inter', size = 12),
        axis.text = element_text(family = 'inter', size = 12),
        legend.key = element_blank(),
        legend.background = element_rect(linewidth = 0.05, color = 'black'),
        panel.background = element_blank(),
        axis.line = element_line(colour = "darkgrey"),
        plot.tag.position = c(230, 99))+
  annotate('text', x = 24, y = 166, label = 'Outliers are represented with a purple triangle.', hjust = 0)+
  annotate( 'text',x = 10, y = 166, label = 'Oxygen concentration was measured using CTD sensors,\n which stands for conductivity, temperature, and density.', hjust = 0)+
  theme(text = element_text(lineheight = 2))
  
```

3.  line graph with element_rect()

```{r}

point <- data.frame(y = 9.36, x = 57.9)
ggplot(data = nutrient_clean_2)+
  geom_point(aes(x = depth, y = dissolved_n, size = temperature),
             color = 'seagreen',  alpha = 0.5)+
  geom_point(data = point, aes(x = x, y = y), color = 'red', size = 4, alpha = 0.25)+
   labs(x = 'Depth (meters)',
       y = ' Concentration (µmol/kg)',
       title = 'Depth Profile of Dissolved Nitrogen',
       size = 'Temperature (°C)')+
  scale_x_reverse()+
  scale_y_continuous(breaks = seq(4,10,1))+
  coord_flip()+
  geom_smooth(aes(x = depth, y = dissolved_n),se = FALSE, color = 'black', linewidth = 0.45)+
  theme_bw()+
  theme(axis.title.x = element_text(family = 'inter', size = 14),
        axis.title.y = element_text(family = 'inter', size = 14),
        plot.title = element_text(family = 'josefin', size = 18, hjust = .5),
        axis.text.x = element_text(family = 'inter', size = 13),
         axis.text.y = element_text(family = 'inter', size = 13),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color = '#E5E4E2', size = 0.25),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(color = '#E5E4E2', size = 0.25))+
    annotate("rect", xmin = 50, xmax = 70, ymin = 8.75, ymax = 10, 
           size = .05, fill = 'lightgrey' ,alpha = 0.25)+
  annotate('text', x = 76, y = 8.80, label = "Descending from the surface, the concentration of Nitrogen\n spikes to 9.36 µmol/kg. At ~57.9 meters below surface\n level, the pH from this oceanographic sample was 8.06.", fontface = 'italic', hjust = 0.5)
```
